object RouteConstants {
    const val URL_LOGIN = "dhaula/api/login.php"
    const val URL_VERIFY_OTP = "dhaula/api/otp.php"
    const val URL_NEWS = "dhaula/api/fetch_news.php"
    const val URL_ADDRESS = "dhaula/api/fetch_user_address.php"
    const val URL_CATEGORIES = "dhaula/api/fetch_category.php"
    const val URL_PRODUCT_LIST = "dhaula/api/fetch_product.php"
    const val URL_ADD_TO_BASKET = "dhaula/api/add_cart.php"
    const val URL_BASKET_LIST = "dhaula/api/fetch_cart.php"
    const val URL_REMOVE_FROM_BASKET="dhaula/api/delete_from_cart.php"
    const val URL_UPDATE_PROFILE = "dhaula/api/update_profile.php"
    const val URL_ADD_ADDRESS = "dhaula/api/user_address.php"
    const val URL_REGISTER = "dhaula/api/register.php"
    const val URL_BECOME_PARTNER = "dhaula/api/become_partner.php"
    const val URL_ADD_ORDER = "dhaula/api/add_order.php"
    const val URL_FETCH_ORDERS = "dhaula/api/fetch_orders.php"
    const val URL_FETCH_ORDER_DETAILS = "dhaula/api/fetch_order_single.php"
    const val URL_ADD_RATING = "dhaula/api/add_rating.php"
    const val URL_CANCEL_ORDER = "dhaula/api/cancel_order.php"
}